language: python
group: travis_latest
dist: xenial

git:
  depth: 25
  quiet: true

python:
  - 3.6

os:
  - linux


install:
- python -m pip install -e .[tests,cov]
- flake8
- mypy .

script: pytest --cov

after_success: coveralls
