name: ci

on:
  push:
    paths:
    - "**/*.py"
    - "**/*.f90"

env:
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0
  CTEST_NO_TESTS_ACTION: error


jobs:

  fortran:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: cmake -Bbuild
    - run: cmake --build build
    - run: ctest --test-dir build -V

  python:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest

  matlab:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        release: [R2024a]

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.release }}

    - uses: actions/checkout@v4

    - name: Run Matlab tests (buildtool)
      if: ${{ matrix.release >= 'R2022b' }}
      timeout-minutes: 10
      uses: matlab-actions/run-build@v2

    - name: Run tests (manual)
      if: ${{ matrix.release < 'R2022b' }}
      timeout-minutes: 10
      uses: matlab-actions/run-tests@v2
      with:
        select-by-folder: +airtools
