name: ci

on:
  push:
    paths:
    - "**/*.py"
    - "**/*.f90"


jobs:

  fortran:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson test -C build

  python:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install GNU Octave
      if: runner.os == 'Linux'
      run: sudo apt install --no-install-recommends octave

    - name: Install Oct2Py
      if: runner.os == 'Linux'
      run: pip install oct2py

    - run: pip install .[tests,lint]

    - run: flake8
    - run: mypy

    - run: pytest
